### ISSUE TITLE
Can I participate as an international student in the UK

### ISSUE THREAD

**Issue by asuzukosi** [jina-ai/GSoC#25]
Hello, please I am an international student studying for a Masters in Computer Science in the UK. This project is closely related to my area of research. Can I partake in this program, GSOCs website is a bit vague to my specific situation. I have a legal right to work in the UK, but my visa allows me to work 20hrs and 40hrs during holidays. Please I would like to have some clarification from the team before submitting my proposal. Thank you

**Comment by Nick17t** [comment]
Given your specific situation, I would recommend that you reach out to GSoC on their [Mail Group](https://groups.google.com/g/google-summer-of-code-discuss) or via email at [gsoc-support@google.com](mailto:gsoc-support@google.com), They will be able to provide you with the necessary information and clarification regarding your concerns.

**Comment by asuzukosi** [comment]
Thank you @Nick17t , I'll do that
